/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const GET_SKILLS = 'GET_SKILLS';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILLS_FAIL = 'GET_SKILLS_FAIL';

export const ADD_SKILL = 'ADD_SKILL';
export const ADD_SKILL_SUCCESS = 'ADD_SKILL_SUCCESS';
export const ADD_SKILL_FAIL = 'ADD_SKILL_FAIL';

export const DELETE_SKILL = 'DELETE_SKILL';
export const DELETE_SKILL_SUCCESS = 'DELETE_SKILL_SUCCESS';
export const DELETE_SKILL_FAIL = 'DELETE_SKILL_FAIL';

export const UPDATE_SKILL = 'UPDATE_SKILL';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';
export const UPDATE_SKILL_FAIL = 'UPDATE_SKILL_FAIL';

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';

export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';

export const GET_MANAGERS = 'GET_MANAGERS';
export const GET_MANAGERS_SUCCESS = 'GET_MANAGERS_SUCCESS';
export const GET_MANAGERS_FAIL = 'GET_MANAGERS_FAIL';

export const ADD_MANAGER = 'ADD_MANAGER';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';
export const ADD_MANAGER_FAIL = 'ADD_MANAGER_FAIL';

export const DELETE_MANAGER = 'DELETE_MANAGER';
export const DELETE_MANAGER_SUCCESS = 'DELETE_MANAGER_SUCCESS';
export const DELETE_MANAGER_FAIL = 'DELETE_MANAGER_FAIL';

export const UPDATE_MANAGER = 'UPDATE_MANAGER';
export const UPDATE_MANAGER_SUCCESS = 'UPDATE_MANAGER_SUCCESS';
export const UPDATE_MANAGER_FAIL = 'UPDATE_MANAGER_FAIL';

export const GET_WORKERS = 'GET_WORKERS';
export const GET_WORKERS_SUCCESS = 'GET_WORKERS_SUCCESS';
export const GET_WORKERS_FAIL = 'GET_WORKERS_FAIL';

export const ADD_WORKER = 'ADD_WORKER';
export const ADD_WORKER_SUCCESS = 'ADD_WORKER_SUCCESS';
export const ADD_WORKER_FAIL = 'ADD_WORKER_FAIL';

export const DELETE_WORKER = 'DELETE_WORKER';
export const DELETE_WORKER_SUCCESS = 'DELETE_WORKER_SUCCESS';
export const DELETE_WORKER_FAIL = 'DELETE_WORKER_FAIL';

export const UPDATE_WORKER = 'UPDATE_WORKER';
export const UPDATE_WORKER_SUCCESS = 'UPDATE_WORKER_SUCCESS';
export const UPDATE_WORKER_FAIL = 'UPDATE_WORKER_FAIL';

export const CHECK_WORKER_SUCCESS = 'CHECK_WORKER_SUCCESS';
export const CHECK_WORKER_FAIL = 'CHECK_WORKER_FAIL';

export const ERROR_CLEAR = 'ERROR_CLEAR';
export const ERROR_SET = 'ERROR_SET';
